prezentacia.pdf: prezentacia.ps
	ps2pdf prezentacia.ps

prezentacia.ps:	prezentacia.dvi
	dvips prezentacia.dvi

prezentacia.dvi: prezentacia.tex
	cslatex prezentacia.tex
	cslatex prezentacia.tex
	cslatex prezentacia.tex
