default: all

.PHONY: all
all: *
	cd transformacia; make
	cd fyzika; make
	cd informatika; make

.PHONY: clean
clean:
	cd transformacia; make clean
	cd fyzika; make clean
	cd informatika; make clean
