default: all

.PHONY: all
all: *
	cd rlc; make
	cd ftir; make
	cd optika; make

.PHONY: clean
clean:
	cd rlc; make clean
	cd ftir; make clean
	cd optika; make clean

.PHONY: full_clean
full_clean:
	cd rlc; make full_clean
	cd ftir; make full_clean
	cd optika; make full_clean
