default: all

.PHONY: all
all: *
	cd transformacia; make
	cd fyzika; make
	cd informatika; make
	cd algoritmy; make

.PHONY: clean
clean:
	cd transformacia; make clean
	cd fyzika; make clean
	cd informatika; make clean
	cd algoritmy; make clean

.PHONY: full_clean
full_clean: clean
	cd transformacia; make full_clean
	cd fyzika; make full_clean
	cd informatika; make full_clean
	cd algoritmy; make full_clean
